typography_spectrum: 0.7839017116930336
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.6494518499821424
  lightness: 0.7014460403006524
  saturation: 0.9845438301563263
  rhythmicContrast: 0.5004930642899126
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.4248909440357238
analytics:
  google: null
  facebook: null
  twitter: null
author:
  email: bernedoodle@outlook.com
  name: Australian Bernedoodle
  url: www.australian-bernedoodle.com
name: Australian bernedoodles
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/9089eed0-1227-4112-9075-391b17145f48.jpg
title: Best of Both Worlds
purpose: []
